### ISSUE TITLE
Is any way to hide the spruce view with animation?

### ISSUE THREAD

**Issue by abelanca95** [willowtreeapps/spruce-ios#81]
Now, I can show collection view items with animation. 
But when I want to close the collection view screen, I want to hide collection view in opposite way with animation.

Is any way to do this?
Thanks a lot!

**Comment by jacksontaylor13** [comment]
Hey @abelanca95! Unfortunately there are no stock animations that work to remove views from the screen. This is something that we are currently working to add. 

However, with Spruce you are essentially applying an animation function to each view on the screen. This animation function can be anything you want so if I wanted to fade each view out and move them left I would use a custom animation function. It would look a little something like this:

```swift
let prepareFunction: PrepareHandler = { view in
     view.alpha = 1.0
     view.transform = CGAffineTransform.identity
}
let animationFunction: ChangeFunction = { view in
    view.alpha = 0.0
    view.transform = CGAffineTransform(translationX: -100.0, y: 0.0)
}
yourView.spruce.animate([.custom(prepareFunction: prepareFunction, animateFunction: animationFunction)])
```

You don't necessarily need the prepare handler, I just like to include it so that if I need to rerun animations or setup the views before hand then Spruce will know what to do.

If we use the code above and apply a `LinearSortFunction` and a `SpringAnimation` type, then we achieve the following:
![issue81response](https://cloud.githubusercontent.com/assets/12803548/24107294/bad2b8fe-0d60-11e7-9627-4d01c722ac8a.gif)

Hopefully this helps. Let me know if you have any questions.

**Comment by abelanca95** [comment]
Wow. Amazing library 👍 
I did it.
Thanks @jacksontaylor13 !
