### ISSUE TITLE
Skip some views

### ISSUE THREAD

**Issue by mixmastertube** [willowtreeapps/spruce-ios#91]
Hi,
didn't find the way to skip some subviews from animating. Is possible somehow?

For example in a collectionview how do I skip the first row to animate?

Thanks so much, it's an awesome library by the way.

**Comment by jacksontaylor13** [comment]
Hi @mixmastertube. Thanks for the kind compliment! Right now the way to skip some views is to use the `exclude` parameter on the animate method (checkout the [Documentation](https://willowtreeapps.github.io/spruce-ios/swift_output/Structs/Spruce.html#/s:FV6Spruce6Spruce7animateFT16withSortFunctionPS_12SortFunction_7prepareGSqFCSo6UIViewT__9animationPS_9Animation_7excludeGSqGSaS2___14recursiveDepthSi10completionGSqFSbT___T_) here).

The current plan is to have this exclude added to each of the methods so that it's easier to call. But I also want to change it to a function rather than just an array of views. So if you have any input on which you would prefer definitely let us know! 👍

**Comment by mixmastertube** [comment]
Didn't see that. Perfect!
Let me try and if I see a better way I will tell you.

Thanks!
